export const getSarcaticMessage = () => {
    const messages = [
        "Ótima tentativa, mas não é assim que se faz isso",
        "Você já considerou mudar de profissão?",
        "Isso foi... diferente.",
        "Ocorreu um problema com o chip de cálculo",
        "Sistema sobrecarregado. Tentando novamente...",
        "Você está indo bem... se seu objetivo é falhar.",
        "Se você acha que está fazendo isso certo, pense novamente.",
        "Aparentemente, suas habilidades em cálculo estão em 'modo avião'.",
        "Você está apenas tentando confundir o sistema, não está?",
        "Ah, uma solução criativa... para um problema inexistente.",
        "Parabéns! Você encontrou uma maneira nova de não fazer nada.",
        "Fico impressionado com sua capacidade de errar de forma tão consistente.",
        "Se essa calculadora tivesse sentimentos, ela estaria chateada com você.",
        "Não tenho certeza se você está tentando calcular ou brincar de esconde-esconde.",
        "Se houvesse um prêmio para erros, você seria um campeão.",
        "Você está redefinindo o significado de cálculo errado.",
        "Espero que você esteja fazendo isso de propósito para entreter a calculadora.",
        "Se eu tivesse um centavo para cada erro, seria rico agora.",
        "Sua habilidade com números é... inovadora, para dizer o mínimo.",
        "Você deve ter um talento especial para errar em grande estilo.",
        "Você sabia que suas tentativas são como arte moderna para cálculos?",
        "Você está criando uma nova forma de arte abstrata com seus erros.",
        "Eu não sabia que cálculos podiam ser tão... criativos.",
        "Se a sua intenção era confundir, parabéns, você conseguiu.",
        "Parece que você está jogando um jogo de adivinhação com a calculadora.",
        "Nunca pensei que veria alguém errar tão artisticamente.",
        "Se calcular fosse um esporte, você seria o campeão mundial.",
        "Cada erro seu é como uma obra-prima do caos num museu de erros.",
        "Você está me impressionando com sua habilidade de errar com estilo.",
        "Eu não sabia que a calculadora tinha um modo de 'frustração'.",
        "Você está inventando novas formas de erro que eu nem sabia que existiam.",
        "Eu só queria dizer: seus erros são realmente inovadores.",
        "Se houvesse uma medalha para erros, você seria o herói da competição.",
        "Cada tentativa sua é como uma peça de teatro de comédia.",
        "Você deve estar treinando para um campeonato mundial de erros.",
        "Parece que você encontrou uma nova maneira de fazer a calculadora rir.",
        "Seu talento para erros é verdadeiramente inspirador.",
        "Você está criando uma nova tendência em erros de cálculo.",
        "Se errar fosse uma arte, você seria um artista renomado.",
        "Eu não sabia que a calculadora tinha um modo de 'frustração máxima'.",
        "Parece que você está tentando criar um novo padrão de erro.",
        "Você está redefinindo o que significa 'errar com estilo'.",
        "Cada tentativa sua é como uma nova definição de 'erro'.",
        "Se houvesse um prêmio para a inovação em erros, você ganharia.",
        "Você está me fazendo pensar que erros podem ser uma forma de arte.",
        "Você está elevando o erro a uma nova forma de expressão criativa.",
        "Se errar fosse uma habilidade, você seria um mestre.",
        "Cada erro seu é como uma nova teoria em 'como não calcular'.",
        "Eu não sabia que erros poderiam ser tão... encantadores.",
        "Você está criando uma nova categoria de erros com suas tentativas.",
        "Parece que você está inventando novos tipos de erro para a calculadora.",
        "Se a frustração fosse um esporte, você seria o campeão olímpico.",
        "Sua habilidade de errar é verdadeiramente notável.",
        "Você está me fazendo questionar a definição de 'cálculo'.",
        "Cada erro seu é como uma nova forma de arte abstrata.",
        "Eu não sabia que a calculadora poderia ficar tão confusa.",
        "Você está criando uma nova forma de entretenimento com seus erros.",
        "Você está revolucionando o conceito de erro com suas tentativas.",
        "Parece que você está fazendo a calculadora passar por um show de comédia.",
        "Se eu tivesse que escolher um campeão de erros, você seria o número um.",
        "Cada tentativa sua é como um novo nível de 'como não fazer isso'.",
    ];
    return messages[Math.floor(Math.random() * messages.length)];
};